Repository cloudnode-pro/ts-client, pull requests merged in 2022-11, with the labels that each got.

#5 Add script for creating release tags
  package-lock.json
  package.json
  scripts/tag.js
  scripts/util/asyncExec.js
Labels: feature, simple

#9 Include credentials in `fetch()` if operation requires token
  README.md
  README.template.md
  browser/Cloudnode.js
  browser/Cloudnode.min.js
  gen/Config.ts
  gen/config.json
  gen/templates/main.mustache
  src/Cloudnode.js
  src/Cloudnode.ts
Labels: bug, documentation, enhancement

#10 Fix bug with body param stringify
  browser/Cloudnode.js
  browser/Cloudnode.min.js
  gen/source.ts
  gen/templates/main.mustache
  src/Cloudnode.js
  src/Cloudnode.ts
Labels: bug, simple

#11 Implement changes from API release
  README.md
  browser/Cloudnode.js
  browser/Cloudnode.min.js
  gen/config.json
  gen/util.ts
  src/Cloudnode.d.ts
  src/Cloudnode.js
  src/Cloudnode.ts
Labels: feature

#12 Use jsdelivr as CDN for browser SDK
  README.md
  gen/config.json
Labels: enhancement

#13 Parse dates from json response
  browser/Cloudnode.js
  browser/Cloudnode.min.js
  gen/templates/main.mustache
  src/Cloudnode.js
  src/Cloudnode.ts
Labels: bug

#14 Test whether the project builds successfully
  .github/workflows/test.yml
  README.md
  README.template.md
  gen/docs.ts
Labels: enhancement

#16 Implement token operations
  README.md
  browser/Cloudnode.js
  browser/Cloudnode.min.js
  gen/docs.ts
  gen/source.ts
  gen/templates/main.mustache
  gen/util.ts
  schema.json
  src/Cloudnode.d.ts
  src/Cloudnode.js
  src/Cloudnode.ts
Labels: feature
